import type { WorldMap } from '../zones';

// Inti's first map. The camp sits in the middle of the forest; the dark
// forest lies off to the north-west and the spirits' forest to the north-east,
// each reached through a narrow neck of trees.
export const bosquePatagonico: WorldMap = {
  name: 'Bosque patagónico',
  ground: ['#303b27', '#2e3926', '#333e29', '#2c3624', '#35402a'],
  zones: {
    C: { name: 'Campamento mapuche', safe: true },
    B: { name: 'Bosque' },
    O: { name: 'Bosque oscuro' },
    E: { name: 'Bosque de los espíritus' },
  },
  plots: [
    '................................................................................................',
    '................................................................................................',
    '................................................................................................',
    '............OOOOOO.O......OOOO..................................................................',
    '............OOOOOOOOOOOOOOOOOO..................................................................',
    '............OOOOOOOOOOOOOOOOOO.......................................EEE......EE................',
    '...........OOOOOOOOOOOOOOOOOOOOO....................................EEEEE...EEEE................',
    '..........OOOOOOOOOOOOOOOOOOOOOOOO.................................EEEEEEEEEEEEE................',
    '.........OOOOOOOOOOOOOOOOOOOOOOOOOOOOO............................EEEEEEEEEEEEEEE...............',
    '.......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...........................EEEEEEEEEEEEEEEEEEE...........',
    '......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO........................EEEEEEEEEEEEEEEEEEEEEEE..........',
    '......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..........................EEEEEEEEEEEEEEEEEEEEEEEE..EE.....',
    '.......OOOOOOOOOOOOOOOOO..OOOOOOOOOOO........................EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.....',
    '.......OOOOOOOOOOOOOOOOO...OOOOOOOOOOOOO.....................EEEEEEEEEEEEEEEEEEEEEEEEEEEEE......',
    '........OOOOOOOOOOOOOOOO...OOOOOOOOOOOOOOO...................EEEEEEEEEEEEEEEEEEEEEEEEEEEEE......',
    '........OOOOOOOOOOOOOOO....OOOOOOOOOOOOOOO...................EEEEEEEEEEE......EEEEEEEEEEEE......',
    '.........OOOOOOOOOOOOO.....OOOOOOOOOOOOOO....................EEEEEEEEEEE......EEEEEEEEEEEE......',
    '.........OOOOOOOOOOOOOO....OOOOOOOOOOOOO.....................EEEEEEEEEEE......EEEEEEEEEEEE......',
    '.........OOOOOOOOOOOOOOO...OOOOOOOOOOOOO.......................EEEEEEEEEEEEEEEEEEEEEEEEEEE......',
    '............OOOOOOOOOOOOOOOOOOOOOOOOOOO.........................EEEEEEEEEEEEEEEEEEEEEEEEEEE.....',
    '.............OOOOOOOOOOOOOOOOOOOOO..............BBBB............EEEEEEEEEEEEEEEEEEEEEEEEEEE.....',
    '.............OOOOOOOOOOOOOOOOOOOOO..............BBBBBBBBB.......EEEEEEEEEEEEEEEEEEEEEEEE........',
    '..............OOOOOOOOOOOOOOOOOO.................BBBBBBBB..........EEEEEEEEEEEEEEEEEEEE.........',
    '...............OOOOOOOOOOOOOOOOO.................BBBBBBBB..BBB.....EEEEEEEEEEEEEEEEEEE..........',
    '................OOOOOOOOOOOOOOOO...............BBBBBBBBBBBBBBBBB.......EEEEEEEEEEEEE............',
    '.................OOOOOOOOOOOO............BBBBBBBBBBBBBBBBBBBBBBB........EEEEEEEEEEE.............',
    '..................BBBOOOOO...............BBBBBBBBBBBBBBBBBBBBBBB........EEEEEEEEEEE.............',
    '..................BBBBBO...........BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.......EEEEEEEEEEE.............',
    '................BBBBBBBB...........BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB........EEEEEEE..............',
    '...............BBBBBBBBB...........BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.......EEEEEE...............',
    '...............BBBBBBBBBBBBB......BBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBB...EEEEEE...............',
    '...............BBBBBBBBBBBBB......BBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBB...............',
    '...............BBBBBBBBBBBBB......BBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBB...............',
    '...............BBBBBBBBBBBBBB....BBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBB..................',
    '............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBB...................',
    '............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBB....................',
    '...........BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBB...................',
    '............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBB....................',
    '..............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBB...................',
    '...............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBB...................',
    '...............BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBB...................',
    '.................BBBBBBBBBBBBBBBB..BBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBB...................',
    '..................BBBBBBBBBBBBB.....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..BBB..............',
    '...................BBBBBBBBBBB.......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..............',
    '......................BBBBBBBB.......BBBBBBBBBBBBBBBBBBBBBBBBBBB..BBBBBBBBBBBBBBBB..............',
    '......................BBBB............BBBBBBBBBBBBBBBBBBBBBBBBB.....BBBBBBBBBBBBBB..............',
    '......................BBBB............BBBBBBBBBBBBBBBBBBBBBBBBB......BBBBBBBBBBBBB..............',
    '........................BB............BBBBBBBBBBBBBBBBBBBBBBBB.......BBBBBBBBBBBBBBBB...........',
    '........................BB................BBBBBBBBBBBBBBBBBBBB.......BBBBBBBBBBBBBBBB...........',
    '..........................................BBBBBBBBBBBBBBBB..BB..........BBBBBBBBBBBBB...........',
    '.............................................BBBBBBBBBBBBB................BBBBBBBBBB............',
    '..............................................BBBBBBBBBBB.................BBBBBBB...............',
    '................................................BBBBBBB...................BBBBBB................',
    '.................................................BBBBB....................BBBBBB................',
    '...........................................................................BBBB.................',
    '................................................................................................',
    '................................................................................................',
  ],
  start: [52, 34],
  objectives: [
    { name: 'Rewe profanado', plot: [19, 10] },
    { name: 'Claro de los ancestros', plot: [82, 13] },
  ],
};
